var frases = [
    'El único modo de hacer un gran trabajo es amar lo que haces',
    'Nunca pienso en las consecuencias de fallar un gran tiro… cuando se piensa en las consecuencias se está pensando en un resultado negativo',
    'El dinero no es la clave del éxito; la libertad para poder crear lo es',
    'Cuanto más duramente trabajo, más suerte tengo',
    'La inteligencia consiste no sólo en el conocimiento, sino también en la destreza de aplicar los conocimientos en la práctica',
    'El trabajo duro hace que desaparezcan las arrugas de la mente y el espíritu',
    'Cuando algo es lo suficientemente importante, lo haces incluso si las probabilidades de que salga bien no te acompañan',
    'Escoge un trabajo que te guste, y nunca tendrás que trabajar ni un solo día de tu vida',
    'Un sueño no se hace realidad por arte de magia, necesita sudor, determinación y trabajo duro',
    'Cuéntamelo y me olvidaré. enséñamelo y lo recordaré. involúcrame y lo aprenderé',
    'La lógica te llevará de la a a la z. la imaginación te llevará a cualquier lugar',
    'A veces la adversidad es lo que necesitas encarar para ser exitoso',
    'Para tener éxito tu deseo de alcanzarlo debe ser mayor que tu miedo al fracaso',
    'Ejecuta tus conocimientos con la maestría del que sigue aprendiendo',
    'Cuando pierdas, no pierdas la lección',
    'No busques los errores, busca un remedio',
    'La vida es una aventura, atrévete',
    'Tu actitud, no tu aptitud, determinará tu altitud',
    'Tienes que hacer las cosas que crees que no puedes hacer',
    'Si te caíste ayer, levántate hoy',
    'Siempre parece imposible... hasta que se hace',
    'Si no pierdes, no puedes disfrutar de las victorias',
    'No dejes que el miedo se interponga en tu camino',
    'Haz de cada día tu obra maestra',
    'No cuentes los días, haz que los días cuenten',
    'El mejor momento del día es ahora',
    'Si la oportunidad no llama, construye una puerta',
    'Deja que cada hombre ejerza el arte que domina',
    'El valor de una idea radica en su uso',
    'Piensa, sueña, cree y atrévete',
    'Con autodisciplina casi todo es posible',
    'Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta',
    'Asegúrate de que colocas tus pies en el lugar correcto, y luego mantente firme',
    'Las ideas pueden cambiar la vida. A veces a lo único que tienes que abrir la puerta es a una buena idea',
    'La mejor manera para empezar es callándote y empezar a hacer',
    'Nadie se desembaraza de un hábito o de un vicio tirándolo de una vez por la ventana; hay que sacarlo por la escalera, peldaño a peldaño',
    'Si te caes siete veces, levántate ocho',
    'La perfección no es alcanzable, pero si perseguimos la perfección podemos conseguir la excelencia',
    'Tienes que esperar cosas de ti mismo antes de poder hacerlas',
    'Transforma tus heridas en sabiduría',
    'La edad no es barrera. Es una limitación que pones en tu mente',
    'Del sufrimiento emergieron las almas más fuertes, los caracteres sólidos tienen cicatrices',
    'El universo no conspira contra ti, pero tampoco se desvía para alinear tu camino',
    'La innovación distingue al líder del seguidor',
    'Si puedes soñarlo, puedes hacerlo',
    'El secreto para salir adelante es comenzar',
    'Los obstáculos son esas cosas atemorizantes que ves cuando apartas los ojos de tu meta',
    'La vida es como montar en bicicleta. para mantener el equilibrio tienes que avanzar',
    'El éxito no es definitivo, el fracaso no es fatídico. Lo que cuenta es el valor para continuar',
    'Sé valiente. Toma riesgos. Nada puede sustituir la experiencia',
    'El futuro pertenece a aquellos que creen en la belleza de sus sueños - Eleanor Roosevelt',
    'El conocimiento es poder',
    'He aprendido que el valor no es la ausencia de miedo, sino el triunfo sobre él. El hombre valiente no es el que no siente miedo, sino el que lo domina',
    'Solo puede ser feliz siempre el que sabe ser feliz con todo',
    'Es la capacidad de resistir a los errores lo que a menudo conduce a un mayor éxito',
    'Aferrarse al rencor es como beber veneno y esperar que otra persona muera',
    'No pares cuando estés cansado. Para cuando hayas terminado',
    'El 80% del éxito se basa simplemente en insistir',
    'Cree que puedes y casi lo habrás logrado',
    'No importa lo que te diga la gente, las palabras y las ideas pueden cambiar el mundo',
    'Si tienes un sueño y crees en él, corres el riesgo de que se convierta en realidad',
    'Nunca se es demasiado viejo para fijar otra meta o para soñar un nuevo sueño',
    'Lo que no te mata, te hace más fuerte',
    'El hombre que mueve montañas comienza cargando pequeñas piedras',
    'Buenos amigos, buenos libros y una conciencia tranquila: esa es la vida ideal',
    'Un optimista ve una oportunidad en toda calamidad, un pesimista ve una calamidad en toda oportunidad',
    'Solo aquellos que se arriesgan a caer pueden conseguir grandes cosas',
    'El éxito es la suma de pequeños esfuerzos, que se repiten día tras día',
    'Sal de tu zona de confort. Solo puedes crecer si estás dispuesto a sentirte raro e incómodo cuando intentas algo nuevo',
    '¿Por qué contentarnos con vivir a rastras cuando sentimos el anhelo de volar?',
    'Entrega siempre más de lo que esperan de ti',
    'Aprovecha las oportunidades que aparezcan, donde quiera que estén',
    'Nunca es demasiado tarde para ser lo que podrías haber sido',
    'Puedo aceptar el fracaso pero no puedo aceptar no intentarlo',
    'La mejor forma de predecir el futuro es creándolo',
    'Un día despertarás y descubrirás que no tienes más tiempo para hacer lo que soñabas. El momento es ahora. Actúa',
    'Hoy eres un lector y mañana serás un líder',
    'Los dos guerreros más poderosos son la paciencia y el tiempo',
    'No puedes derrotar a la persona que nunca se rinde',
    'El secreto de tu éxito está determinado por tu agenda diaria',
    'Recordar que vas a morir, es la mejor manera que conozco para no pensar que tienes algo que perder. Ya estás desnudo. No hay ninguna razón para no seguir a tu corazón',
    'Se lo suficientemente valiente para vivir de forma creativa. El lugar creativo donde nadie ha estado',
    'Cuando dejo ir lo que soy, me convierto en lo que debería ser',
    'Apunta a la luna. Si fallas, podrías dar a una estrella',
    'Existe al menos un rincón del universo que con toda seguridad puedes mejorar, y eres tú mismo',
    'El verdadero buscador crece y aprende, y descubre que siempre es el principal responsable de lo que sucede',
    'Escribir es un oficio que se aprende escribiendo',
    'La forma más rápida de cambiar es convivir con personas que ya son como quieres ser',
    'La felicidad no es algo que pospones para el futuro; es algo que diseñas para el presente',
    'La alegría es contagiosa y siempre consigue descubrir una solución donde la lógica sólo encontró una explicación para el error',
    'Vive la vida que amas. Ama la vida que vives',
    'El éxito no es la clave de la felicidad. La felicidad es la clave del éxito',
    'Unas palabras amables, un libro cálido y una sonrisa honesta pueden hacer milagros',
    'La verdadera felicidad consiste en hacer el bien',
    'El otoño se convierte en una nueva primavera cuando cada hoja es una flor',
    'El éxito es encontrar satisfacción en dar un poco más de lo que se recibe',
    'La alegría reside en la alegría del logro y en la emoción del esfuerzo creativo',
    'La verdadera motivación procede de trabajar en cosas que nos importan',
    'La felicidad no ocurre por casualidad, sino por elección',
    'No tienes poder sobre los acontecimientos exteriores, pero sí sobre tu mente. Aprende esto, y encontrarás tu fuerza',
    'La buena vida es una forma de pensar',
    'Puedes ser feliz allí donde estés',
    'El término «felicidad» perdería todo su significado si no fuese compensado por la tristeza',
    'Alguien se sienta en la sombra porque alguien plantó un árbol hace mucho tiempo',
    'Avanza con confianza en la dirección de tus sueños',
    'La diligencia es la madre de la buena suerte',
    'Sólo se vive una vez. Pero si lo haces bien, una vez basta',
    'Da el primer paso con fe. No tienes que ver todas las escaleras, sólo da el  primer paso',
    'Trabajar duro por algo que no te importa se llama estrés. Trabajar duro por algo que te importa de verdad se llama pasión',
    'El éxito depende del esfuerzo',
    'Intenta y falla, pero nunca falles en intentarlo',
    'No quiero ganarme la vida, quiero vivir',
    'La vida no es un problema a ser resuelto, sino una realidad a experimentar',
    'Háblate a ti mismo como harías con alguien a quien amas',
    'Por más difícil que parezca la vida, siempre hay algo que puedes hacer y en lo que puedes tener éxito',
    'El fracaso se convierte en éxito si aprendes de él',
    'La mala noticia es que el tiempo vuela. La buena noticia es que tú eres el piloto',
    'La única manera de encontrar los límites de lo posible es ir más allá de lo imposible',
    'Casi todas las cosas buenas que suceden en el mundo, nacen de una actitud de aprecio por los demás',
    'Donde reina el amor, siempre sobran las leyes',
    'Amarse a uno mismo es el comienzo de una larga vida romántica', 
    'Nada de lo que vistes es más importante que tu sonrisa',
    'En cada forma de vida existe el deseo del amor', 
    'Todos nos necesitamos los unos a los otros', 
    'Antes moriría de pasión que de aburrimiento',
    'Solo hay una felicidad en la vida, amar y ser amado',
    'El amor propio es la fuente de todos los tipos de amor',
    'Cambias tu vida al cambiar tu corazón',
    'La sencillez es una forma de humildad y la sencillez es una señal de la verdadera grandeza',
    'El alma que hablar puede con los ojos, también puede besar con la mirada',
    'El que ama, se hace humilde. Aquellos que aman, por decirlo de alguna manera, renuncian a una parte de su narcisismo',
    'Sólo porque alguien no te ame como tú quieres, no significa que no te ame con todo su ser',
    'El amor no mira con los ojos, sino con el alma',
    'La mejor forma de olvidar las malas cosas de la vida es aprender a recordar las cosas buenas',
    'Árbol de la esperanza, mantente firme',
    'El éxito es la capacidad de ir de fracaso en fracaso sin perder el entusiasmo',
    'Tus acciones positivas combinadas con los pensamientos positivos generan éxitos',
    'Qué maravilloso es que nadie tenga que esperar ni un segundo para empezar a mejorar el mundo',
    'Un solo rayo de sol es suficiente para apartar muchas sombras',
    'Cuando piensas en positivo, cosas buenas ocurren',
    'No podemos ayudar a todos, pero todo el mundo puede ayudar a alguien',
    'Sé el cambio que quieres ver en el mundo',
    'Cualquier cosa que la mente del hombre puede concebir y creer, puede ser conseguida',
    'Si supiera que el mundo se acaba mañana, yo, hoy todavía, plantaría un árbol',
    'Es impresionante. La vida cambia muy rápido, de un modo positivo, si la dejas',
    'La palabra «no» solo significa que empieces otra vez en un nivel superior',
    'La grandeza nace de pequeños comienzos',
    'Pon tu corazón, mente y alma incluso en los actos más pequeños. Ese es el secreto del éxito'
]
window.onload = () => {
    document.getElementById ('frase').innerHTML = frases [Math.floor (Math.random () * frases.length)]
}